### ISSUE TITLE
Data division ratio affects binning results

### ISSUE THREAD

**Issue by YasinZhao** [abhayspawar/featexp#1]
train_test_split =0.3, there is no problem. But when set the ratio is 0.25 or 0.5, something is wrong.
![image](https://user-images.githubusercontent.com/16828608/48052998-7403cf80-e1e4-11e8-9c68-9d55b1bae873.png)

**Comment by abhayspawar** [comment]
This could be because of small data size or very less variation in a feature. Some edge case is not being taken care of. 

Are you working on some open sourced data? Would make it easier for me to debug if you can share the data.

**Comment by YasinZhao** [comment]
Thanks for your reply. I am so sorry that the data set was obtained in a competition and may not be published. It's great work, I will follow it. Thank you again.
