### ISSUE TITLE
Citing featexp

### ISSUE THREAD

**Issue by e184633** [abhayspawar/featexp#11]
Thank you very much for putting together a nice library. Would there be a better way of citing featexp than this repository?

**Comment by abhayspawar** [comment]
Unfortunately, I don't have a paper or something which you can cite. Maybe be the medium blog post in the readme?

**Comment by e184633** [comment]
Ok, thanks, maybe for future you could obtain a [doi](https://guides.github.com/activities/citable-code/) for citing?

**Comment by abhayspawar** [comment]
Here: https://zenodo.org/badge/doi/10.5281/zenodo.2616757.svg
Thanks for this!
