### ISSUE TITLE
KeyError: "Column 'target' does not exist!"

### ISSUE THREAD

**Issue by mrxuehb** [abhayspawar/featexp#13]
Hello, I am trying to use this wonderful tool, but the error occurs as '**KeyError: "Column 'target' does not exist!"**'. I am pretty sure that 'target' is in train data as a column.
Could you help me with this? Many thanks.
![image](https://user-images.githubusercontent.com/5998563/55337829-f82b5c00-54d1-11e9-92b9-ffbe5c8c3bc8.png)
![image](https://user-images.githubusercontent.com/5998563/55337856-06797800-54d2-11e9-8bab-fb170c2f01f8.png)

**Comment by abhayspawar** [comment]
This error is coming from data_test not having 'target' column. data_train is fine.
