### ISSUE TITLE
Matplotlib outputs

### ISSUE THREAD

**Issue by e184633** [abhayspawar/featexp#14]
Hi again Abhay, 

I ended up locally playing with the library since it was not allowing manipulation of the output figures (like changing resolution and saving pdf outputs as opposed to png). It is quite a quick fix I think, just need to restructure a bit the `draw_plots` function.

**Comment by abhayspawar** [comment]
Hi Farida,
Please feel free to send across a PR or the code. I'll have a look.

Thanks a lot!

**Comment by duanhuihui2009** [comment]
> Hi again Abhay,
> 
> I ended up locally playing with the library since it was not allowing manipulation of the output figures (like changing resolution and saving pdf outputs as opposed to png). It is quite a quick fix I think, just need to restructure a bit the `draw_plots` function.

I made it. Save all the codes in the base.py file and rename it to featexp_new.py, Add a line of plt.savefig('../my_fig.png') just before the 'plt.show()'  line in the draw_plots function. 
import featexp_new and run the function below:

import featexp_new 
featexp_new.get_univariate_plots(data=data_train, target_col='target', features_list=['column'], bins=10)

**Comment by abhayspawar** [comment]
I'll try adding this asap. Thanks for your inputs!
