### ISSUE TITLE
Colab version compatibility

### ISSUE THREAD

**Issue by gig67** [abhayspawar/featexp#15]
Great package. I have some issues when running `!pip install featexp`  in google Colab.
I get the following messages:

> ERROR: google-colab 1.0.0 has requirement pandas~=0.24.0, but you'll have pandas 0.23.4 which is incompatible.
>ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
>ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
>Successfully installed featexp-0.0.5 matplotlib-3.0.2 numpy-1.15.4 pandas-0.23.4
>WARNING: The following packages were previously imported in this runtime:
  [matplotlib,mpl_toolkits,numpy,pandas]
>You must restart the runtime in order to use newly installed versions.

As a consequence (I believe) commands like `dataframe.head()` no longer work.

**Comment by abhayspawar** [comment]
Will update the dependency to latest pandas soon. In the meanwhile can you try reinstalling pandas, etc. to their latest ones after installing featexp. I think it should work fine.

**Comment by abhayspawar** [comment]
Requirements are updated in the github repo. I'll release a new version of the package on pip soon.
