### ISSUE TITLE
Implementing sample/data weight

### ISSUE THREAD

**Issue by chnzhangrui** [abhayspawar/featexp#16]
Hi Abhay,
I appreciate your great effort on publishing your code. I wonder if there is a way to implement weights for each data point since this is often the case in my domain. Thanks.
Cheers,
Rui

**Comment by abhayspawar** [comment]
There's currently no way to do this. A hack is to stick to integer weights. Say a data point has weight n, then repeat that data point n times in your data. And use this data to create the plots.

**Comment by abhayspawar** [comment]
I'll look into if this can added as a feature to the package. Thanks.
