### ISSUE TITLE
cannot import name 'get_trend_stats_feature'

### ISSUE THREAD

**Issue by wmmxk** [abhayspawar/featexp#17]
First, thanks for developing this package. I tried the "get_univariate_plots" function and it worked but I can not import the "get_trend_stats_feature" function. Do you have ideas?

**Comment by abhayspawar** [comment]
Can you post the error message here?

**Comment by wmmxk** [comment]
Thanks for your reply. The error is not very informative. Here is the error: "ImportError: cannot import name 'get_trend_stats_feature'". Does that mean there is no function named "get_trend_stats_feature"?

**Comment by abhayspawar** [comment]
Sorry. Replying pretty late. You're using the wrong the function name. It's 'get_trend_stats'.
