### ISSUE TITLE
dependent library version old?

### ISSUE THREAD

**Issue by pjgao** [abhayspawar/featexp#2]
It seems that `numpy` `matplotlib` 's version maybe a little old?
![snipaste_2018-11-07_20-32-49](https://user-images.githubusercontent.com/22350313/48131932-b9033100-e2cc-11e8-82cf-d4e7eff67a37.png)

**Comment by abhayspawar** [comment]
Thanks for pointing out. Will change it to latest.

**Comment by NahuelGrasso** [comment]
Great package!!
I have the same issues, I wonder if it should be updated again
![image](https://user-images.githubusercontent.com/11187909/62278164-ef19af80-b41d-11e9-92b0-a3159b819393.png)

**Comment by abhayspawar** [comment]
Will update soon. Hope you're still able to use it by reinstalling the latest version of numpy and pandas after installing featexp.

**Comment by NahuelGrasso** [comment]
Thanks! :) please let us know when it happens!
