### ISSUE TITLE
featexp_demo file not exist error

### ISSUE THREAD

**Issue by wubinbai** [abhayspawar/featexp#22]
--------------------------------
FileNotFoundErrorTraceback (most recent call last)
<ipython-input-3-bc7bf8e2b172> in <module>()
----> 1 X_train, X_test, y_train, y_test, train_users, test_users = import_and_create_train_test_data()
.....(blablabla)
FileNotFoundError: File b'demo/data/application_train.csv' does not exist

why? any knows how to solve?

**Comment by abhayspawar** [comment]
You'll have to download the data from kaggle first and save it in this location.
