### ISSUE TITLE
AssertionError: `result` has not been initialized.

### ISSUE THREAD

**Issue by snehamaheshwari07** [abhayspawar/featexp#23]
Getting this error again and again while executing the command:
stats = get_trend_stats(data=data_train, target_col='target', data_test=data_split[0])

**Comment by snehamaheshwari07** [comment]
@abhayspawar

**Comment by snehamaheshwari07** [comment]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-23-a2b7caaf1a4f> in <module>
----> 1 get_univariate_plots(data=data_train,target_col='target',data_test=data_split[0])

/opt/conda/lib/python3.7/site-packages/featexp/base.py in get_univariate_plots(data, target_col, features_list, bins, data_test)
    221             print(cols + ' is categorical. Categorical features not supported yet.')
    222         elif cols != target_col and data[cols].dtype != 'O':
--> 223             univariate_plotter(feature=cols, data=data, target_col=target_col, bins=bins, data_test=data_test)
    224 
    225 

/opt/conda/lib/python3.7/site-packages/featexp/base.py in univariate_plotter(feature, data, target_col, bins, data_test)
    184         if has_test:
    185             grouped_test = get_grouped_data(input_data=data_test.reset_index(drop=True), feature=feature,
--> 186                                             target_col=target_col, bins=bins, cuts=cuts)
    187             trend_corr = get_trend_correlation(grouped, grouped_test, feature, target_col)
    188             print(' {:^100} '.format('Train data plots'))

/opt/conda/lib/python3.7/site-packages/featexp/base.py in get_grouped_data(input_data, feature, target_col, bins, cuts)
     41 
     42     grouped = input_data.groupby([cut_series], as_index=True).agg(
---> 43         {target_col: [np.size, np.mean], feature: [np.mean]})
     44     grouped.columns = ['_'.join(cols).strip() for cols in grouped.columns.values]
     45     grouped[grouped.index.name] = grouped.index

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/generic.py in aggregate(self, func, *args, **kwargs)

/opt/conda/lib/python3.7/site-packages/pandas/core/base.py in _aggregate(self, arg, *args, **kwargs)
    417                 """
    418                 aggregate a 1-dim with how
--> 419                 """
    420                 colg = self._gotitem(name, ndim=1, subset=subset)
    421                 if colg.ndim != 1:

/opt/conda/lib/python3.7/site-packages/pandas/core/base.py in _agg(arg, func)
    384                     # {'ra': ['mean']}
    385 
--> 386                     # not ok
    387                     # {'ra' : { 'A' : 'mean' }}
    388                     if isinstance(v, dict):

/opt/conda/lib/python3.7/site-packages/pandas/core/base.py in _agg_1dim(name, how, subset)
    368             # eg. {'A' : ['mean']}, normalize all to
    369             # be list-likes
--> 370             if any(is_aggregator(x) for x in compat.itervalues(arg)):
    371                 new_arg = compat.OrderedDict()
    372                 for k, v in compat.iteritems(arg):

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/generic.py in aggregate(self, func, *args, **kwargs)

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/generic.py in _aggregate_multiple_funcs(self, arg)

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/generic.py in aggregate(self, func, *args, **kwargs)

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in _python_agg_general(self, func, *args, **kwargs)
    924                 # This would normally not be triggered
    925                 # except if the udf is trying an operation that
--> 926                 # fails on *some* columns, e.g. a numeric operation
    927                 # on a string grouper column
    928 

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/ops.py in agg_series(self, obj, func)

/opt/conda/lib/python3.7/site-packages/pandas/core/groupby/ops.py in _aggregate_series_fast(self, obj, func)

pandas/_libs/reduction.pyx in pandas._libs.reduction.SeriesGrouper.get_result()

AssertionError: `result` has not been initialized.

**Comment by abhayspawar** [comment]
@snehamaheshwari07 I think there is some issue with the data that you are using. Can try these things to figure out the issue:
1. run only for a set of features by passing a list using 'features_list' input param for get_trend_stats
2. Maybe iterate over each feature one by one to figure out which feature it is failing for.
3. Use only the top 100 rows of train and test data and see if it works.

**Comment by snehamaheshwari07** [comment]
Don't know why but It is throwing error for variables with more NULL values. (with more I mean more then 50% values are NULL)
It is working when I remove those variables. 
Thank you :)
