### ISSUE TITLE
why bins  are not Equal frequency 

### ISSUE THREAD

**Issue by Emily-Zh** [abhayspawar/featexp#24]
AS the function `get_univariate_plots` says, the bins should be equal frequency, but many plots in `featexp_demo.ipynb` behave the opposite,  for example, 'Plots for CNT_CHILDREN'、'Plots for AMT_INCOME_TOTAL'

**Comment by Emily-Zh** [comment]
@abhayspawar     At your convenience, would you please give me a hand with the above question? Thank you for your assistance

**Comment by abhayspawar** [comment]
Hi,
Sorry for the late response. That happens when the feature cannot be split into equal population bins. Think about a feature with values 0 and 1. 70% of values are say 1. This feature cannot be split into say 5 bins of equal population.

**Comment by Emily-Zh** [comment]
Thanks for your reply. I understand the situation that you say above, but I'm still wondering...
for example,  the feature `AMT_INCOME_TOTAL` is continuous and can be split into 5 bins of equal population, but the plot in `featexp_demo.ipynb` is like this , obviously not equal population, why?
![image](https://user-images.githubusercontent.com/27850645/95810441-8b8a5200-0d43-11eb-96e3-262bee83a223.png)
@abhayspawar  thanks for your time!

**Comment by abhayspawar** [comment]
The reason for this is the same ie the income is not continuous enough to create equal population bins. The feature looks continuous, but in a lot of regions it is actually discrete with a lot of customers having same value. I'm guessing if you try fewer bins, it will give equal population bins. Hope that makes sense.
