### ISSUE TITLE
代码中test相关文件名的问题

### ISSUE THREAD

**Issue by Emily-Zh** [abhayspawar/featexp#26]
在get_dataloader.py中，定义test_name='testb'，但原始test数据文件夹里（百度云下载的），数据文件前缀都是test_a，没有testb开头的，代码执行时会报文件找不到的错误
还有在main_LR.py的load_dataset中，也是‘/test/testb_base.csv'这样的引用，，但并没有testb这种数据

请问这个testb是否实际是指test_a这样开头的文件？谢谢！

@wj19971997

**Comment by wj19971997** [comment]
官方给的那个test_b的文件文件名改成testB_click_log.csv




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Emily-Zh"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 晚上6:15
收件人: "abhayspawar/featexp"<featexp@noreply.github.com&gt;; 
抄送: "、"<1402129410@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: [abhayspawar/featexp] 代码中test相关文件名的问题 (#26)





 
在get_dataloader.py中，定义test_name='testb'，但原始test数据文件夹里（百度云下载的），数据文件前缀都是test_a，没有testb开头的，代码执行时会报文件找不到的错误
 还有在main_LR.py的load_dataset中，也是‘/test/testb_base.csv'这样的引用，，但并没有testb这种数据
 
请问这个testb是否实际是指test_a这样开头的文件？谢谢！
 
@wj19971997

**Comment by wj19971997** [comment]
对的，testb是复赛的测试数据，可能我上传的时候没有上传testb的数据，你代码里文件名改成test_a开头就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Emily-Zh"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 晚上6:15
收件人: "abhayspawar/featexp"<featexp@noreply.github.com&gt;; 
抄送: "、"<1402129410@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: [abhayspawar/featexp] 代码中test相关文件名的问题 (#26)





 
在get_dataloader.py中，定义test_name='testb'，但原始test数据文件夹里（百度云下载的），数据文件前缀都是test_a，没有testb开头的，代码执行时会报文件找不到的错误
 还有在main_LR.py的load_dataset中，也是‘/test/testb_base.csv'这样的引用，，但并没有testb这种数据
 
请问这个testb是否实际是指test_a这样开头的文件？谢谢！
 
@wj19971997

**Comment by Emily-Zh** [comment]
I‘m so sorry to bother you, because that i just realize the issue is not in the right position, and i really don't konw how it happen😂
@abhayspawar

**Comment by abhayspawar** [comment]
haha no worries
