### ISSUE TITLE
Issue with get_trend_stats()

### ISSUE THREAD

**Issue by michaelabehsera** [abhayspawar/featexp#4]
Hey,
What am I doing wrong here?
https://cl.ly/466adfd96d75 I am using the dataset in the article on credit risk.
Thanks,

**Comment by abhayspawar** [comment]
Nothing is wrong here. Features for which it said 'only one bin created' have only one value or close to zero variation and hence, bins can't be created. And trend correlation also can't be calculated from only 1 bin. 
You'll still get your 'stats' dataframe. 0 correlation will be returned for such features in 'stats' dataframe. 

Also, featexp currently supports only numeric features and 'stats' dataframe will be returned with only numeric features' information. Categorical features will be ignored.
