### ISSUE TITLE
Bug in get_trend_stats()

### ISSUE THREAD

**Issue by mmeendez8** [abhayspawar/featexp#5]
I am getting this error using get_trend_stats()

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-30-8cf9ede42a1d> in <module>()
> ----> 1 stats = get_trend_stats(data=train, target_col='CANTIDAD_DIR_REP_BIG_RT', data_test=test)
>       2 stats
> 
> ~/anaconda3/lib/python3.6/site-packages/featexp/base.py in get_trend_stats(data, target_col, features_list, bins, data_test)
>     247             ignored.append(feature)
>     248         else:
> --> 249             cuts, grouped = get_grouped_data(input_data=data, feature=feature, target_col=target_col, bins=bins)
>     250             trend_changes = get_trend_changes(grouped_data=grouped, feature=feature, target_col=target_col)
>     251             if has_test:
> 
> ~/anaconda3/lib/python3.6/site-packages/featexp/base.py in get_grouped_data(input_data, feature, target_col, bins, cuts)
>      36         # if reduced_cuts>0:
>      37         #     print('Reduced the number of bins due to less variation in feature')
> ---> 38         print(cuts)
>      39         cut_series = pd.cut(input_data[feature], cuts)
>      40     else:
> 
> ~/anaconda3/lib/python3.6/site-packages/pandas/core/reshape/tile.py in cut(x, bins, right, labels, retbins, precision, include_lowest, duplicates)
>     226         bins = _convert_bin_to_numeric_type(bins, dtype)
>     227         if (np.diff(bins) < 0).any():
> --> 228             raise ValueError('bins must increase monotonically.')
>     229 
>     230     fac, bins = _bins_to_cuts(x, bins, right=right, labels=labels,
> 
> ValueError: bins must increase monotonically.

I checked cuts value and this is its content:
[475836.1, 897023.3999999999, 1256710.22, 1334681.24, 1838614.84, 1838614.8399999999, 3230684.84]
So it seems there is a bug since two cuts have the same value!

**Comment by abhayspawar** [comment]
Hey @mmeendez8, saw your PR for this issue. Thanks for fixing this! Will merge it soon.

**Comment by mmeendez8** [comment]
Fixed in #6
