### ISSUE TITLE
Bug in xgboost DMatrix 

### ISSUE THREAD

**Issue by StarJu** [abhayspawar/featexp#7]
dtrain = xgb.DMatrix(X_test, label=y_test, missing=np.nan)
dtest = xgb.DMatrix(X_train, label=y_train, missing=np.nan)

The X_test is for dtrain not X_train?? Is there anything wrong?

**Comment by abhayspawar** [comment]
Yes, it should be the other way around. I'll correct it and post updated results. Thanks for pointing out.
