### ISSUE TITLE
bug in get_trend_stats 

### ISSUE THREAD

**Issue by anzhizh** [abhayspawar/featexp#8]
I meet this problem: ValueError: missing values must be missing in the same location both left and right sides. Can you help me solve this wrong? Thank you very much

**Comment by anzhizh** [comment]
ValueError: missing values must be missing in the same location both left and right sides

**Comment by abhayspawar** [comment]
Hmmm that's weird. Can you try running get_trend_stats on one feature at a time using a for loop? And catch which feature leads to this error and maybe why. Maybe there's some edge case which isn't being handled.
