### ISSUE TITLE
ModuleNotFoundError: No module named 'featexp'

### ISSUE THREAD

**Issue by MartinPetrov8** [abhayspawar/featexp#9]
I am on python 3.6 and pip installed featexp and it cannot import - i am getting a ModuleNotFoundError

**Comment by kning** [comment]
could you post a little more detail on the error message you're getting? Worked fine for me.

**Comment by rwolbeck** [comment]
I would suggest posting your code, everything is working fine for me as well.

**Comment by MartinPetrov8** [comment]
Hello, sorry for the late reply, it was an issue with my numpy. I re-installed anaconda and all works fine. Thank you
